openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:8080/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://localhost:8090/v1
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /health:
    get:
      summary: return health status
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON object of health status
          content:
            application/json:
              schema:
                oneOf:
                  - SuccessStatus
                  - Error1Status
                  - Error2Status

components:
  schemas:
    StatusBase:
      type: object
      properties:
        statusType:
          type: string

    SuccessStatus:
      allOf:
        - $ref: '#components/schemas/StatusBase'
        - type: object
          properties:
            healthDetail:
              type: string

    Error1Status:
      type: object
      properties:
        statusType:
          type: string