rootProject.name = "java-gradle"
println("executing settings.gradle.kts")
include("playground")
include("io-netty")
include("io-webflux")
include("lang-jvm")
include("lang-kotlin")
include("msa-service")
include("msa-service-discover")
include("msa-service-feign-client")
include("msa-spring-cloud")
include("msa-spring")
include("msa-spring-native")
include("mw-cassandra-bench")
include("mw-elasticsearch")
include("tool-gradle")
include("tool-auto-script")
include("tool-logger")
include("mw-redis")
include("tool-snowflakeid")
