rootProject.name = "java-gradle"
include("playground")
include("sparkfun")
include("auto-script")
include("spring")
include("netty")
include("jvm-test")
include("my-spring-boot-autoconfigure")
include("my-spring-boot-starter")
include("es")