rootProject.name = "java-gradle"
println("executing settings.gradle.kts")
include("playground")
include("auto-script")
include("spring")
include("netty")
include("jvm-test")
include("my-spring-boot-autoconfigure")
include("my-spring-boot-starter")
include("es")
include("gradle-learn")
include("learn-kotlin")
include("springcloudlearn")
include("cassandra-bench")
include("service-discover")
include("service-foo")
include("service-feign-client")
