server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.50.42:3306/test_db
    #    url: jdbc:mysql://localhost:3306/hueconnect
    username: root
    #    username: root
    #    password: HPaADeEl6K6Mo+ib
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 100
    connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
    idle-timeout: 10000 #maximum idle time for connection
    max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
    auto-commit: true #default auto-commit behavior.
  flyway:
    enabled: true
  sql:
    init:
      continue-on-error: true

#  flyway:
##    url: jdbc:mysql://192.168.50.42:3306/test_db2
##    user: chen
##    password: HPaADeEl6K6Mo+ib
#    driver-class-name: com.mysql.cj.jdbc.Driver

