server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.50.42:8761/eureka}
spring:
  application:
    name: feign-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      enabled: true
  openfeign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic
loadbalancer:
  client:
    name: foo