service: serverless-example
frameworkVersion: ~3.39

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    config: './esbuild.config.js'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: src/main.handler
    environment: 
      DB: pgEnhanced
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'