redis:
  host: localhost
  port: 6379
kafka:
  host: localhost
  port: 7199
cassandra:
  host: localhost
  port: 9042
zookeeper:
  host: localhost
  port: 2181
server:
  port: 8090

mysql:
  host: 127.0.0.1
  user: chen
  password: HPaADeEl6K6Mo+ib