spring:
  flyway:
    enabled: true
    locations: classpath:/migration
  datasource:
    # pg config
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGDB:localhost:5432}/twi
    hikari:
      schema: twi
    username: postgres
    password: password
    maximum-pool-size: 10
    connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
    idle-timeout: 10000 #maximum idle time for connection
    max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
#    auto-commit: true #default auto-commit behavior.

twi:
  fanout:
    url: ${FANOUT_URL:http://localhost:8081}
  user:
    url: ${USER_URL:http://localhost:8083}

server:
  port: ${PORT:8080}
