server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081

sentry:
  dsn: "http://16a9ab9acf814c04a924991f52ed0996@127.0.0.1:9000/2"
  logging: true

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test_db2
    url: jdbc:mysql://localhost:3306/hueconnect
#    username: chen
    username: root
#    password: HPaADeEl6K6Mo+ib
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
##    url: jdbc:mysql://192.168.50.42:3306/test_db2
##    user: chen
##    password: HPaADeEl6K6Mo+ib
#    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  id: SampleApp
apollo:
  meta: "http://localhost:8080"
  property:
    order:
      enable: true

timeout: 9999
timeout2: 9999

