service: aws-node-http-api-project
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
