service: aws-node-http-api-project
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-webpack


provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore